version: '3.8'

services:
  rust:
    container_name: rust_env
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    working_dir: /workspace
    image: myrust
    # user: 1000:1000
    # environment:
    #   USER: okubo
    volumes:
      - .:/workspace
      - rust-target:/workspace/target

volumes:
  rust-target: