[package]
name = "at_cd1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
cli_test_dir = "0.1.7"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "atc1"
path = "src/atc1.rs"